[build-system]
requires = ["setuptools>=82.0.1", "wheel>=0.48.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tescam-cli"
version = "0.1.0"
description = "Cross-platform interactive CLI for composing multi-camera dashcam footage"
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-3.0-only"
license-files = ["LICENSE", "NOTICE"]
authors = [
  {name = "MAGRATHEAN UK LTD", email = "contact@magrathean.uk"}
]
dependencies = []
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Environment :: Console",
  "Topic :: Multimedia :: Video",
]

[project.scripts]
tescam-cli = "tescam_cli.cli:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["tescam_cli*"]
